version: 0.0
os: linux

files:
  - source: deploy
    destination: /home/ubuntu/deploy
    overwrite: true

permissions:

  - object: /home/ubuntu/deploy
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: root
 
  ValidateService:
    - location: deploy/validate.sh
      timeout: 60
      runas: root